name: Deploy Image to GHCR

on:
  push:
    branches:
      - "main"
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/gonssalves/red-ficker:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      -
        name: Install dependency
        run: pip install requests
      -
        run: |
          docker run -d -p 5000:5000 -e FLASK_ENV=development ghcr.io/gonssalves/red-ficker:latest
          sleep 5 
      -
        name: Run tests
        run: python tests/test_example.py

  send:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{secrets.GCP_AUTH_KEY}}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Pull image from GHCR'
        run: |
          docker pull ghcr.io/gonssalves/red-ficker:latest

      - name: 'Tag image for GCR'
        run: |
          docker tag ghcr.io/gonssalves/red-ficker:latest gcr.io/cinfo-devops-2023-2/red-ficker:latest

      - name: 'Push image to GCR'
        run: |
          docker push gcr.io/cinfo-devops-2023-2/docker/red-ficker:latest