name: Deploy Image to GHCR

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Se necessário, login no GitHub Container Registry
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      # Set up Docker Buildx, Build and push
      # (Coloque aqui as etapas para construir e enviar a imagem para o GHCR)

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      ficker:
        image: ghcr.io/gonssalves/ficker:latest
        env:
          FLASK_ENV: development
        ports:
          - 5000:5000
    steps:
      - name: Esperar até o contêiner estar pronto
        run: dockerize -wait tcp://localhost:5000 -timeout 1m

      - name: Executar comandos dentro do contêiner
        run: docker exec ficker echo "Hello from inside the container"
