name: Deploy Image to GHCR

on:
  push:
    branches:
      - "main"
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/gonssalves/ficker:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      -
        name: Install dependency
        run: pip install requests
      -
        run: |
          docker run -d -p 5000:5000 -e FLASK_ENV=development ghcr.io/gonssalves/ficker:latest
          sleep 5 
      -
        name: Run tests
        run: python tests/test_example.py

  send:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Authenticate to Google Cloud and configure Docker
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: cinfo-devops-2023-2
          service_account_key: ${{secrets.GCP_AUTH_KEY}}
          export_default_credentials: true
          
      # - name: Pull image from GHCR
      #   run: |
      #     docker pull ghcr.io/gonssalves/ficker:latest

      # - name: Tag image for GCR
      #   run: |
      #     docker tag ghcr.io/gonssalves/ficker:latest gcr.io/your-project-id/ficker:latest

      # - name: Push image to GCR
      #   run: |
      #     docker push gcr.io/your-project-id/ficker:latest