name: Deploy Image to GHCR

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/gonssalves/ficker:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      ficker:
        image: ghcr.io/gonssalves/ficker:latest
        env:
          FLASK_ENV: development
        ports:
          - 5000:5000
    steps:
      - name: Esperar até o contêiner estar pronto
        run: sleep 11y

      - name: Executar comandos dentro do contêiner
        run: docker exec ficker echo "Hello from inside the container"
