name: Deploy Image to Cloud Run

on:
  push:
    branches:
      - "main"
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/gonssalves/red-ficker:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      -
        name: Install dependency
        run: pip install requests
      -
        run: |
          docker run -d -p 5000:5000 -e FLASK_ENV=development ghcr.io/gonssalves/red-ficker:latest
          sleep 5 
      -
        name: Run tests
        run: python tests/test_example.py

  push-to-gcr:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - 
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{secrets.GCP_AUTH_KEY}}'
      - 
        name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - 
        name: 'Use gcloud CLI'
        run: 'gcloud info'
      - 
        name: 'Pull image from GHCR'
        run: |
          docker pull ghcr.io/gonssalves/red-ficker:latest
      - 
        name: 'Tag image for GCR'
        run: |
          docker tag ghcr.io/gonssalves/red-ficker:latest us-central1-docker.pkg.dev/cinfo-devops-2023-2/docker/red-ficker:latest
      - 
        name: 'Google Cloud CLI'
        run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin us-central1-docker.pkg.dev/cinfo-devops-2023-2/docker/red-ficker
      - 
        name: 'Push image to GCR'
        run: |
          docker push us-central1-docker.pkg.dev/cinfo-devops-2023-2/docker/red-ficker:latest
 
  deploy-cloud-run:
    runs-on: ubuntu-latest
    needs: push-to-gcr 
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - 
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
    - 
      id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'hello-cloud-run'
        image: 'us-central1-docker.pkg.dev/cinfo-devops-2023-2/docker/red-ficker:latest'
    - 
      name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'